---
- name: install gnupg2
  become: yes
  apt:
    name: gnupg2
    state: present

- name: add lazygit ppa
  become: yes
  apt_repository:
    repo: 'ppa:lazygit-team/release'

- name: install lazygit
  become: yes
  apt:
    name: lazygit
    state: present
